### ISSUE TITLE
Issue: 401 - Invalid client secret is provided

### ISSUE THREAD

**Issue by alex-frankel** [neilpeterson/azure-blueprints-pipeline-tasks#5]
When I run this task, I keep getting a 401. I am using a service connection which I've tried specifying in YAML (in build) and in the UI (for release), but neither are working. I ran it with debug and 

What seems to be the relevant error:
`error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 6ef7f788-7671-4305-97cb-f3f5b7384900`

I also see that some of these are blank:
`"spnObjectId":"","appObjectId":""`

So I guess something is wrong with my service connection?

This is the full dump:
```
2019-04-08T16:52:42.2928624Z ##[debug]Evaluating condition for step: 'Create Azure Blueprint'
2019-04-08T16:52:42.2942327Z ##[debug]Evaluating: succeeded()
2019-04-08T16:52:42.2942558Z ##[debug]Evaluating succeeded:
2019-04-08T16:52:42.2942968Z ##[debug]=> True
2019-04-08T16:52:42.2943260Z ##[debug]Result: True
2019-04-08T16:52:42.2943836Z ##[section]Starting: Create Azure Blueprint
2019-04-08T16:52:42.3272834Z ==============================================================================
2019-04-08T16:52:42.3273128Z Task         : Create Azure Blueprint
2019-04-08T16:52:42.3273203Z Description  : Creates an Azure Blueprint
2019-04-08T16:52:42.3273287Z Version      : 1.0.0
2019-04-08T16:52:42.3273351Z Author       : Neil Peterson
2019-04-08T16:52:42.3273429Z Help         : 
2019-04-08T16:52:42.3273498Z ==============================================================================
2019-04-08T16:52:44.2848539Z ##[debug]VstsTaskSdk 0.11.0 commit 7ff27a3e0bdd6f7b06690ae5f5b63cb84d0f23f4
2019-04-08T16:52:44.7671692Z ##[debug]INPUT_CONNECTEDSERVICENAME: '2010be28-4fba-4774-bc8d-bd4a611057da'
2019-04-08T16:52:44.7830810Z ##[debug]ENDPOINT_URL_2010be28-4fba-4774-bc8d-bd4a611057da: 'https://management.azure.com/'
2019-04-08T16:52:44.7870804Z ##[debug]ENDPOINT_AUTH_2010be28-4fba-4774-bc8d-bd4a611057da: '********'
2019-04-08T16:52:44.7972407Z ##[debug]ENDPOINT_DATA_2010be28-4fba-4774-bc8d-bd4a611057da: '{"subscriptionId":"d56e652e-758d-480a-8f0d-47f230264b4c","subscriptionName":"Visual Studio Ultimate with MSDN","environment":"AzureCloud","scopeLevel":"Subscription","creationMode":"Manual","azureSpnRoleAssignmentId":"","azureSpnPermissions":"","spnObjectId":"","appObjectId":"","environmentUrl":"https://management.azure.com/","galleryUrl":"https://gallery.azure.com/","serviceManagementUrl":"https://management.core.windows.net/","resourceManagerUrl":"https://management.azure.com/","activeDirectoryAuthority":"https://login.microsoftonline.com/","environmentAuthorityUrl":"https://login.windows.net/","graphUrl":"https://graph.windows.net/","managementPortalUrl":"https://manage.windowsazure.com/","armManagementPortalUrl":"https://portal.azure.com/","activeDirectoryServiceEndpointResourceId":"https://management.core.windows.net/","sqlDatabaseDnsSuffix":".database.windows.net","AzureKeyVaultDnsSuffix":"vault.azure.net","AzureKeyVaultServiceEndpointResourceId":"https://vault.azure.net","StorageEndpointSuffix":"core.windows.net","EnableAdfsAuthentication":"false"}'
2019-04-08T16:52:44.8066962Z ##[debug]INPUT_PUBLISHBLUEPRINT: 'true'
2019-04-08T16:52:44.8098395Z ##[debug]INPUT_VERSION: 'Increment'
2019-04-08T16:52:44.8128261Z ##[debug]INPUT_BLUEPRINTCREATIONLOCATION: 'managementGroup'
2019-04-08T16:52:44.8197174Z ##[debug]INPUT_MANAGEMENTGROUPNAME: 'root'
2019-04-08T16:52:44.8221667Z ##[debug]INPUT_BLUEPRINTNAME: 'AppNetwork'
2019-04-08T16:52:44.8228970Z ##[debug]INPUT_BLUEPRINTPATH: './Example Blueprints/AppNetwork/blueprint.json'
2019-04-08T16:52:44.8258581Z ##[debug]INPUT_ARTIFACTSPATH: './Example Blueprints/AppNetwork/artifacts'
2019-04-08T16:52:44.8503832Z ##[debug]POST https://login.microsoftonline.com/***/oauth2/token with -1-byte payload
2019-04-08T16:52:45.3588019Z ##[debug]Caught exception from task script.
2019-04-08T16:52:45.3631545Z ##[debug]Error record:
2019-04-08T16:52:45.4888869Z ##[debug]Invoke-RestMethod : {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 6ef7f788-7671-4305-97cb-f3f5b7384900\r\nCorrelation ID: 56dc967c-8e7a-41c5-8dfe-e0eaed3cf1f8\r\nTimestamp: 2019-04-08 16:52:44Z","error_codes":[7000215],"timestamp":"2019-04-08 16:52:44Z","trace_id":"6ef7f788-7671-4305-97cb-f3f5b7384900","correlation_id":"56dc967c-8e7a-41c5-8dfe-e0eaed3cf1f8"}
2019-04-08T16:52:45.4901926Z ##[debug]At D:\a\_tasks\CreateBlueprint_1a8623d7-1d5c-423c-9d92-5e9587bbb02a\1.0.0\createBlueprint.ps1:35 char:10
2019-04-08T16:52:45.4916056Z ##[debug]+ $Token = Invoke-RestMethod -Method Post -Uri $RequestAccessTokenUri - ...
2019-04-08T16:52:45.4932626Z ##[debug]+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-04-08T16:52:45.4948113Z ##[debug]    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt    pWebRequest) [Invoke-RestMethod], WebException
2019-04-08T16:52:45.4963833Z ##[debug]    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe    ll.Commands.InvokeRestMethodCommand
2019-04-08T16:52:45.4994170Z ##[debug]Script stack trace:
2019-04-08T16:52:45.5041822Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreateBlueprint_1a8623d7-1d5c-423c-9d92-5e9587bbb02a\1.0.0\createBlueprint.ps1: line 35
2019-04-08T16:52:45.5056221Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-04-08T16:52:45.5072381Z ##[debug]at <ScriptBlock>, <No file>: line 22
2019-04-08T16:52:45.5086346Z ##[debug]at <ScriptBlock>, <No file>: line 18
2019-04-08T16:52:45.5100626Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-04-08T16:52:45.5124471Z ##[debug]Exception:
2019-04-08T16:52:45.5175720Z ##[debug]System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2019-04-08T16:52:45.5189823Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2019-04-08T16:52:45.5203090Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2019-04-08T16:52:45.5825597Z ##[error]The remote server returned an error: (401) Unauthorized.
2019-04-08T16:52:45.5835545Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (401) Unauthorized.
2019-04-08T16:52:45.5851075Z ##[debug]Processed: ##vso[task.complete result=Failed]
2019-04-08T16:52:45.6411594Z ##[section]Finishing: Create Azure Blueprint
```

**Comment by neilpeterson** [comment]
Are you creating the blueprint at a management group and if so can you make the service principal an owner of the management group?

![image](https://user-images.githubusercontent.com/7844635/55755577-4d470f00-5a8a-11e9-9d73-3ac92bcb62f9.png)

And then that the pipeline service connection is configured to use this service principal? This requires creating the service connection with the ‘advanced’ options.

![image](https://user-images.githubusercontent.com/7844635/55755664-98f9b880-5a8a-11e9-8da9-1097d45fb550.png)

**Comment by alex-frankel** [comment]
The blueprint is at an MG and the service principal is an owner of that MG, I double checked, and I’m pretty confident the service connection is configured correctly (see screenshots).

Is it expected that those two properties are empty strings like that? It seems like it is not grabbing the SPN/service connection info properly.

![image](https://user-images.githubusercontent.com/11078275/55829993-e0049f80-5ac4-11e9-80b9-8e5881a65cd7.png)

![image](https://user-images.githubusercontent.com/11078275/55830007-e561ea00-5ac4-11e9-91a5-c76b03d753e9.png)

**Comment by neilpeterson** [comment]
I've just tested in my environment and these values are also blank (however task was successful).

~Walking through the configuration from scratch, end to end, I noticed that when creating the Azure Pipeline Service Connection we can create a new service connection (without providing creds) and scope it to a Management Group, which will create the SP and grant ownership over the management group.~

~I've tried this and the task was successful. Can you give this a shot to troubleshoot any potential service principal issues?~

**Comment by neilpeterson** [comment]
@alex-frankel sorry, advice in the last comment is not good.

I've updated the readme with end to end instructions which have worked in my environment. I can help troubleshoot next week in yours.

Thanks

**Comment by ajf214** [comment]
So given what was troubleshooted, it's possible there still may be an issue with using an *existing* SPN. Though it's also possible since I was not upgraded automatically from 1.0 to 1.1 that could have resolved it to.

Also, DevOps updating their service connection UX to support MGs also could have resolved it.

I think you can consider this closed until I can repro it again

**Comment by neilpeterson** [comment]
Closing this for now.
